# Generated by Django 5.0.14 on 2026-08-14 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_passwordresettoken_organizationinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_CHANGED', 'Password Changed'), ('USER_INVITED', 'User Invited'), ('INVITATION_RESENT', 'Invitation Resent'), ('INVITATION_REVOKED', 'Invitation Revoked'), ('INVITATION_ACCEPTED', 'Invitation Accepted'), ('ROLE_CHANGED', 'Role Changed'), ('USER_ADDED_TO_ORGANIZATION', 'User Added To Organization'), ('USER_REMOVED_FROM_ORGANIZATION', 'User Removed From Organization'), ('PERMISSION_DENIED', 'Permission Denied')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='logs_auditl_organiz_4ee2bb_idx'), models.Index(fields=['action', '-created_at'], name='logs_auditl_action_62042e_idx')],
            },
        ),
    ]
