# Generated by Django 5.0.14 on 2026-07-30 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIIncidentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated executive summary and security summary.",
                    ),
                ),
                (
                    "root_cause",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated technical probable root cause analysis.",
                    ),
                ),
                (
                    "severity_prediction",
                    models.CharField(
                        blank=True,
                        default="MEDIUM",
                        help_text="AI-predicted severity classification.",
                        max_length=50,
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Calculated risk score between 0.0 and 100.0.",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="AI prediction confidence score between 0.0 and 1.0.",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list,
                        help_text="Structured remediation and prevention recommendations.",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Incident Analysis",
                "verbose_name_plural": "AI Incident Analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
