# Generated by Django 5.0.14 on 2026-07-30 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0001_initial"),
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "severity_prediction",
                    models.CharField(blank=True, default="MEDIUM", max_length=50),
                ),
                ("risk_score", models.FloatField(default=0.0)),
                (
                    "incident_category",
                    models.CharField(blank=True, default="Other", max_length=100),
                ),
                ("root_cause_analysis", models.TextField(blank=True, default="")),
                ("impact_analysis", models.TextField(blank=True, default="")),
                ("recommended_actions", models.JSONField(default=list)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident AI Analysis",
                "verbose_name_plural": "Incident AI Analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
