# Generated by Django 5.0.14 on 2026-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_incidentanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentanalysis',
            name='knowledge_citations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='incidentanalysis',
            name='previous_resolutions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='incidentanalysis',
            name='similar_incidents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
