# Generated by Django 5.0.14 on 2026-07-30 13:23

import apps.knowledge.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "accounts",
            "0002_organization_alter_user_options_alter_user_managers_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chunk_index", models.IntegerField(db_index=True)),
                ("content", models.TextField()),
                ("token_count", models.IntegerField(default=0)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Metadata including chunk index, document ID, page number, headings, tags.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="DocumentEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("embedding", apps.knowledge.models.VectorField(default=list)),
                (
                    "embedding_model",
                    models.CharField(default="mock-embed-v1", max_length=100),
                ),
                ("vector_dimension", models.IntegerField(default=1536)),
                (
                    "chunk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="knowledge.documentchunk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Embedding",
                "verbose_name_plural": "Document Embeddings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("file", models.FileField(upload_to="knowledge_docs/%Y/%m/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("DOCX", "DOCX"),
                            ("TXT", "TXT"),
                            ("MD", "Markdown"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSING", "Processing"),
                            ("INDEXED", "Indexed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True, default="")),
                ("page_count", models.IntegerField(default=0)),
                ("word_count", models.IntegerField(default=0)),
                ("chunk_count", models.IntegerField(default=0)),
                ("embedding_count", models.IntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_documents",
                        to="accounts.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Document",
                "verbose_name_plural": "Knowledge Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="knowledge.knowledgedocument",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
    ]
