import React from 'react';
import { Sparkles, ArrowRight } from 'lucide-react';

export interface CopilotSuggestedQuestionsProps {
  questions: string[];
  onSelectQuestion: (question: string) => void;
  disabled?: boolean;
}

/**
 * Interactive suggested follow-up questions generated by the AI Engine.
 * Clicking a suggestion immediately submits it to the chat session.
 */
export const CopilotSuggestedQuestions: React.FC<CopilotSuggestedQuestionsProps> = React.memo(
  ({ questions, onSelectQuestion, disabled = false }) => {
    if (!questions || questions.length === 0) return null;

    return (
      <div className="mt-3 pt-3 border-t border-zinc-800/80">
        <div className="flex items-center gap-1.5 mb-2 text-xs font-semibold text-indigo-400">
          <Sparkles className="w-3.5 h-3.5" />
          <span>Suggested Follow-up Investigations</span>
        </div>

        <div className="flex flex-wrap gap-2">
          {questions.map((question, index) => (
            <button
              key={`${index}-${question.substring(0, 15)}`}
              onClick={() => !disabled && onSelectQuestion(question)}
              disabled={disabled}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-zinc-900/90 hover:bg-indigo-500/10 border border-zinc-800 hover:border-indigo-500/40 text-left text-xs text-zinc-300 hover:text-indigo-200 transition-all disabled:opacity-50 disabled:cursor-not-allowed group"
              aria-label={`Ask suggested question: ${question}`}
            >
              <span>{question}</span>
              <ArrowRight className="w-3.5 h-3.5 text-zinc-500 group-hover:text-indigo-400 transition-colors shrink-0" />
            </button>
          ))}
        </div>
      </div>
    );
  }
);

CopilotSuggestedQuestions.displayName = 'CopilotSuggestedQuestions';
